services:
  api:
    build: .
    container_name: vehicle_control_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=vehicle_control_db;Username=${POSTGRES_USER:-Admin};Password=${POSTGRES_PASSWORD:-Senha123}
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-Admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Senha123}
      - POSTGRES_DB=${POSTGRES_DB:-vehicle_control_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge